### ISSUE TITLE
Script is detecting only alpha versions

### ISSUE THREAD

**Issue by renandecarlo** [wppconnect-team/wa-version#605]
It seems the script is no longer generating main and beta versions

**Comment by icleitoncosta** [comment]
> It seems the script is no longer generating main and beta versions

Yes, because there are no longer any 'main' versions, only completely beta versions. The new versioning format for WhatsApp is as it is now. Soon, we will change the alpha to main; it was just a nomenclature we used. I am waiting for a change in the WhatsApp core to be sure of this, but so far, that change hasn't been made.

Regarding the previous beta versions, there are no longer any completely beta versions; there are only beta features. In other words, it is the same version, but you either opt into the beta or not. If you opt in, the beta features are enabled; if you don't, they are not.
