### ISSUE TITLE
stills not working with whatsapp-web.js

### ISSUE THREAD

**Issue by rogerthedeveloper** [wppconnect-team/wa-version#616]
My bot stopped working, any file I picked up from /html folder for webLocalCache not working on whatsapp-web.js v2.24.0

**Comment by kkmillan** [comment]
I've been having the same issue since Saturday. I've been jumping to different fixes as stated but I still keep getting the error/s after scanning the QR for login.
Current error: `Cannot read properties of undefined (reading 'default')`

 [2885](https://github.com/pedroslopez/whatsapp-web.js/issues/2885) [2789](https://github.com/pedroslopez/whatsapp-web.js/issues/2789)

**Comment by kkmillan** [comment]
Temporary Fix Update:

Edited the code to the node module from [here](https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-2034333596)

**Comment by rizkihermansyah83** [comment]
> Temporary Fix Update:
> 
> Edited the code to the node module from [here](https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-2034333596)

thanks @kkmillan ,, it working for me.. maturwuon sanget....

**Comment by palbano30** [comment]
Isso funcionou pra mim, também

**Comment by kiron111** [comment]
this solution solved the problem:
[](https://github.com/pedroslopez/whatsapp-web.js/pull/2816#issuecomment-2204732956)

**Comment by rogerthedeveloper** [comment]
its great to have a solution topic, using new 2.3 version in that branch, We hope to get it on a main release soon!
